from typing import Protocol


class DatagramWrapper(Protocol):
    def __init__(self, payload: bytes) -> None: ...

    @property
    def payload(self) -> bytes: ...
    @property
    def src_address(self) -> str: ...
    @property
    def src_port(self) -> int: ...
    @property
    def dst_address(self) -> str: ...
    @property
    def dst_port(self) -> int: ...

    @property
    def ip_header_length(self) -> int: ...
    @property
    def payload_length(self) -> int: ...
